[gcp]
type = "service_account"
project_id = "streamlit-input-text"
private_key_id = "0ae7b654f560dc9b5ac70c5a2b2450fa64bd4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8WhOgyZ4tOOW9
akso5P5suEOZvNidJQ1Beiw7FlnzEWX6/JtSMKAdwcRVb8cvjn2Yei0YGGBLYdQC
BSTvfpkq0w2kUcdFR2Nm7z/RvVoHqHWVQA5aVwrDkPunFnzfkpqIesC4GaAot3Lr
hj+3pPD1BdYZH92wiSXNx0tzITqA1gPka+zxa2aWIJ/R0vSPKNkLQ+fNczV8kb43
lr1l2jbiFU/J7kDUWFeYmJZcL4DFYPY5N6di2vxOAYxZ+Ff4PaLnLDUnJcytGGSM
6MrcS1ZsKdyR0I+/SibD1Eedb63Oif/VyCMg6GcUUo3Qos97YU5wlWMRcowQ9YBm
QfY38r7hAgMBAAECggEABQ8FnERop1NHYap4q/er2P9WmsrxJcCogKaHiJYQQrso
D4Z4T3ah3kVlgLFDWsTLcmxu80ji+9377oqf1CovcpsqMHcdJdWwgZkRuuWIhPsi
c/3n73I2BkxJuKedy/gT3Brb5os9ph+jNQMtM+v4qBleMjI3vIrlGofslVeCSufT
c7j+WiQ8MiehJWsODWSNRSsbKdehgVR8AdEz4qXyYFiHZRo7DVGOipc1LNtBcVbu
pNekQdKbH1zO9IYJ/tW9YWHs2BtqXhHA6LOc+P3f9SRBmHNYoNGk3p7Oetu4mR3B
0OUkLJWTuaG5rU20RWqU7T0v8X4CONUi+JBYJHOSbwKBgQDjn4rzHDgKFJJpS6BU
Y6LExGu7Oezd6ffE1kDqVRCGqLjxUdZ10nPzNGbeKA+R4K7U2+dN5h+k+MUqapfe
VajJbqhsQMythSD6do6LM1zJydjBtvVy2TsjkS3JfB+zNZMZG9dakG9iPiqVWgEm
1ryScLOvr+Tplety/3o9pDwTawKBgQDT1TZjIvNFFPX9W+sAGIdQ5L0GgKW7Ie9S
ta9D7NDPt8lwVtdpuX7MQ1xwwjTI3vgW+VrCIxZlIVLUyPUEEIZSlLXIjkUs/9sO
fYofL+YYz/RBRQlBL7WDxwwLVEKazMljXwWk5gcw04Vreob1ovGfZeRKyHWnf0cR
r+QZtnFV4wKBgQCxowukCCyvqThNlihsU0lud79/YIg68uFaqr4EYhhAjqGuKmjM
kE3OyeFRlD/6XzbxhR/xChs9+qqcHI2ihITxljs4KCXTcOa4sBc0CQRrsetH2gmY
9HCTpDPwXr66c5/1Y2XgFoHmUI+Y+KGXdtO5EN0ZyZJCvK3/k+MJAgekOwKBgCUq
9OcCG+MUIXE57orOwvdbmxsH+YxTEPXXMRBe/ehkW/DdG+DODkRy0UZrnO1dyfPl
/pmvpF9MMIdrVypGZ/sXYqn05IhXwCzTtCdytRHHcxj8rvoED/o2M5PNTf5xTiik
ZI4hWkOj6XYJQqLY20JXk23XrGUePO8KiKBGVa53AoGBAN8SlbjyDWFyZFbnCJiR
wp6TDjsGnmUJhV+hTRKssZfp/zU145fsasb6ZKuiuZ03HnUMGFl55NXxuJ0adMpP
rPFbjSc62opMl4abcaP/RK1/1Ah1FZ6p7jTQfF2pRjhbYeqbUReDbSOxOXDxSaWD
CyvDFrFt/k6ioH8owS1qalpF
-----END PRIVATE KEY-----"""
client_email = "streamlit-service@streamlit-input-text.iam.gserviceaccount.com"
client_id = "101267901448253971103"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-service@streamlit-input-text.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
